agents:
  - name: Robot1
    velocity: 1
    resources: wifi, bluetooth
    location: 0, 0

  - name: Robot2
    velocity: 1
    resources: bluetooth
    location: 4, 4

tasks:
  - name: Zad1
    resources: wifi
    duration: 4
    precedence: /
    earliest_start_time: 0
    latest_finish_time: 70
    location: 5, 5

  - name: Zad2
    resources: wifi, bluetooth
    duration: 2
    precedence: Zad1, Zad6
    earliest_start_time: 0
    latest_finish_time: 100
    location: 4, 2

  - name: Zad3
    resources: bluetooth
    duration: 9
    precedence: Zad2, Zad5
    earliest_start_time: 20
    latest_finish_time: 90
    location: 9, 7

  - name: Zad4
    resources: bluetooth
    duration: 8
    precedence: /
    earliest_start_time: 0
    latest_finish_time: 70
    location: 11, 10

  - name: Zad5
    resources: wifi, bluetooth
    duration: 3
    precedence: Zad4
    earliest_start_time: 25
    latest_finish_time: 70
    location: 9, 5

  - name: Zad6
    resources: wifi
    duration: 4
    precedence: /
    earliest_start_time: 0
    latest_finish_time: 100
    location: 6, 7